import type { SearchCardMeta } from "../search/search-card-meta";

/**
 * Every card on the Pools page, in display order — the command-palette search
 * metadata for {@link PoolsShell}, which places the cards itself. A card added
 * there must be listed here to be searchable; the coverage spec fails until it is.
 */
export const POOLS_CARDS: readonly SearchCardMeta[] = [
  {
    id: "pools-tvl",
    title: "useInventoryTvl",
    kind: "read",
    section: "Protocol aggregates",
    summary: "Custodial TVL across the whole system, from the inventory service.",
    keywords: ["getInventoryTvl", "TVL", "total value locked", "inventory"],
  },
  {
    id: "pools-volume",
    title: "useMarketInfo",
    kind: "read",
    section: "Protocol aggregates",
    summary: "Traded value across every market, over 24 hours and since launch.",
    keywords: ["getMarketInfo", "volume", "24h volume"],
  },
  {
    id: "pools-open-interest",
    title: "useNotionalCapAll",
    kind: "read",
    section: "Protocol aggregates",
    summary: "Open and still-available notional across every market the solver quotes.",
    keywords: ["getNotionalCapAll", "open interest", "notional cap", "capacity"],
  },
  {
    id: "pools-catalog",
    title: "useListingMarkets",
    kind: "read",
    section: "Listing catalog",
    summary: "Search, filter, sort and page the catalog of listed pools.",
    keywords: ["getListingMarkets", "useSupportsListingService", "catalog", "listings", "discover", "markets"],
  },
  {
    id: "method-getInventoryTvlHistory",
    title: "useInventoryTvlHistory",
    kind: "read",
    section: "Pool detail",
    summary: "One pool's custodial TVL over time.",
    keywords: ["getInventoryTvlHistory", "TVL history", "chart"],
  },
  {
    id: "method-getPoolTradeVolume",
    title: "useTradeVolume",
    kind: "read",
    section: "Pool detail",
    summary: "One pool's traded notional per day.",
    keywords: ["getTradeVolume", "volume", "daily volume", "chart"],
  },
  {
    id: "pool-revenue",
    title: "useSolverRevenue",
    kind: "read",
    section: "Pool detail",
    summary: "One pool's solver revenue, split into hedger-fee and funding shares.",
    keywords: ["getSolverRevenue", "revenue", "hedger fee", "funding"],
  },
  {
    id: "method-getPoolRewardChart",
    title: "usePoolRewardChart + usePoolTotalReward",
    kind: "read",
    section: "Pool detail",
    summary: "A pool's daily LP rewards and its trailing-window total.",
    keywords: ["usePoolRewardChart", "usePoolTotalReward", "getPoolRewardChart", "rewards", "APR"],
  },
  {
    id: "pool-detail",
    title: "Pool detail",
    kind: "read",
    section: "Pool detail",
    summary: "One pool's positions, quote book, limit orders, trade history, deposits and withdrawals.",
    keywords: [
      "useListingMarketDetail",
      "usePoolQuotes",
      "useSearchTpSlOrders",
      "usePoolTradeHistory",
      "usePoolTransactions",
      "getPoolTransactions",
      "positions",
      "open quotes",
      "limit orders",
      "trade history",
      "deposits and withdrawals",
    ],
  },
  {
    id: "method-authenticateListing",
    title: "authenticateListing",
    kind: "write",
    section: "Listing service",
    summary: "Sign in to the listing service once; every signed-in card reuses the token.",
    keywords: ["useAuthenticateListing", "sign in", "SIWE", "login", "access token"],
  },
  {
    id: "method-getListingConfig",
    title: "getListingConfig",
    kind: "read",
    section: "Listing service",
    summary: "Listing fee, deposit guidance, rate limits and supported deposit chains.",
    keywords: ["useListingConfig", "listing fee", "deposit chains", "rate limits"],
  },
  {
    id: "method-getWeeklyListingLimit",
    title: "getWeeklyListingLimit",
    kind: "read",
    section: "Listing service",
    summary: "How many new pools can still be listed this week.",
    keywords: ["useWeeklyListingLimit", "weekly limit", "quota"],
  },
  {
    id: "method-getListingStatus",
    title: "getListingStatus",
    kind: "read",
    section: "Listing service",
    summary: "Where a market sits in the listing pipeline, polled while it progresses.",
    keywords: ["useListingStatus", "listing status", "pipeline"],
  },
  {
    id: "method-addMarket",
    title: "addMarket",
    kind: "write",
    section: "Listing service",
    summary: "List a new token as a pool, then seed its deposit wallet.",
    keywords: ["useAddMarket", "Create pool", "list token", "new listing"],
  },
  {
    id: "method-getUserListingMarkets",
    title: "useUserListingMarkets",
    kind: "read",
    section: "Your pools",
    summary: "Every pool you have a deposit address for, with your deposit, share and revenue.",
    keywords: ["getUserListingMarkets", "Your pools", "my pools"],
  },
  {
    id: "method-getUserRewardChart",
    title: "useUserRewardChart + useUserTotalReward",
    kind: "read",
    section: "Your pools",
    summary: "Your LP rewards over time across every pool, plus the 30-day total.",
    keywords: ["useUserRewardChart", "useUserTotalReward", "getUserRewardChart", "my rewards"],
  },
  {
    id: "method-getUserTransactions",
    title: "getUserTransactions",
    kind: "read",
    section: "Your pools",
    summary: "Every pool deposit and withdrawal you have made, newest first.",
    keywords: ["useUserTransactions", "my transactions", "deposits", "withdrawals", "history"],
  },
  {
    id: "method-getUserProfit",
    title: "getUserProfit",
    kind: "read",
    section: "Your position in a pool",
    summary: "Your LP position in one pool: balance, rewards, shares and pending withdrawal.",
    keywords: ["useUserProfit", "Your pool balance", "LP position", "claimable"],
  },
  {
    id: "method-getDepositAddress",
    title: "getDepositAddress",
    kind: "read",
    section: "Your position in a pool",
    summary: "Get or create your deposit wallet for one pool.",
    keywords: ["useDepositAddress", "useListingMarketDetail", "Deposit address", "deposit"],
  },
  {
    id: "method-updateListingMarketConfig",
    title: "updateListingMarketConfig",
    kind: "write",
    section: "Your position in a pool",
    summary: "Submit your max-leverage and buyback opinion for one pool.",
    keywords: [
      "useListingMarketConfig",
      "useListingMarketConfigProjection",
      "useUpdateListingMarketConfig",
      "Market config",
      "max leverage",
      "buyback",
    ],
  },
  {
    id: "method-withdrawLp",
    title: "withdrawLp",
    kind: "write",
    section: "Your position in a pool",
    summary: "Queue a withdrawal of your LP shares from one pool.",
    keywords: ["useWithdrawLp", "Withdraw", "LP shares"],
  },
  {
    id: "method-cancelWithdraw",
    title: "cancelWithdraw",
    kind: "write",
    section: "Your position in a pool",
    summary: "Cancel a queued LP withdrawal before it settles.",
    keywords: ["useCancelWithdraw", "usePoolTransactions", "Cancel withdrawal", "pending withdrawal"],
  },
  {
    id: "method-claimProfit",
    title: "claimProfit",
    kind: "write",
    section: "Your position in a pool",
    summary: "Claim your accrued LP rewards to a sub-account as USDC.",
    keywords: ["useClaimProfit", "Claim", "rewards", "USDC"],
  },
  {
    id: "method-getClaimHistory",
    title: "getClaimHistory",
    kind: "read",
    section: "Your position in a pool",
    summary: "Your past reward claims, newest first.",
    keywords: ["useClaimHistory", "Claim history", "past claims"],
  },
  {
    id: "method-refundMarket",
    title: "refundMarket",
    kind: "write",
    section: "Your position in a pool",
    summary: "Reclaim your deposit on a rejected pool.",
    keywords: ["useRefundMarket", "Refund", "rejected"],
  },
  {
    id: "method-retryListing",
    title: "retryListing",
    kind: "write",
    section: "Your position in a pool",
    summary: "Re-submit a rejected pool for listing instead of refunding it.",
    keywords: ["useRetryListing", "useRetryListingInfo", "Retry listing", "rejected"],
  },
];
