export default {
  index: "Overview",
  "-- reads": { type: "separator", title: "Reads" },
  "get-quote-tpsl": "getQuoteTpSl",
  "get-tpsl-config": "getTpSlConfig",
  "get-tpsl-signing-spec": "getTpSlSigningSpec",
  "get-tpsl-delete-signing-spec": "getTpSlDeleteSigningSpec",
  "-- writes": { type: "separator", title: "Writes" },
  "set-quote-tpsl": "setQuoteTpSl",
  "delete-quote-tpsl": "deleteQuoteTpSl",
  "-- websocket": { type: "separator", title: "WebSocket" },
  "watch-tpsl-notifications": "watchTpSlNotifications",
  "parse-tpsl-frame": "parseTpSlFrame",
  "-- signing": { type: "separator", title: "Signing & validation" },
  "validate-tpsl": "validateTpSl",
  "generate-tpsl-salt": "generateTpSlSalt",
  "sign-tpsl-request": "signTpSlRequest",
  "to-signable-tpsl-message": "toSignableTpSlMessage",
  "build-tpsl-delete-message": "buildTpSlDeleteMessage",
  "build-conditional-order-message": "buildConditionalOrderMessage",
  "build-conditional-order-leg": "buildConditionalOrderLeg",
  "price-slippage-calculation": "priceSlippageCalculation",
  "-- grouped": { type: "separator", title: "Grouped TP/SL" },
  "to-group-tpsl-children": "toGroupTpSlChildren",
  "summarize-quote-group-tpsl": "summarizeQuoteGroupTpSl",
  "to-group-tpsl-orders": "toGroupTpSlOrders",
  "estimate-group-tpsl-return": "estimateGroupTpSlReturn",
  "plan-group-tpsl": "planGroupTpSl",
  "plan-group-tpsl-delete": "planGroupTpSlDelete",
  "-- types": { type: "separator", title: "Types" },
  "tpsl-notification": "TpSlNotification",
  "raw-tpsl-notification": "RawTpSlNotification",
  "quote-tpsl-row": "QuoteTpSlRow",
  "quote-tpsl": "QuoteTpSl",
  "tpsl-config": "TpSlConfig",
  "tpsl-signing-spec": "TpSlSigningSpec",
  "set-tpsl-side": "SetTpSlSide",
  "tpsl-validation": "TpSlValidation",
  "validate-tpsl-inputs": "ValidateTpSlInputs",
  "tpsl-conditional-order-message": "TpSlConditionalOrderMessage",
  "tpsl-conditional-order-leg": "TpSlConditionalOrderLeg",
  "tpsl-delete-message": "TpSlDeleteMessage",
  "tpsl-signed-request": "TpSlSignedRequest",
  "tpsl-price-type": "TpSlPriceType",
  "tpsl-info-state": "TpSlInfoState",
  "group-tpsl-child": "GroupTpSlChild",
  "group-tpsl-desired-sides": "GroupTpSlDesiredSides",
  "quote-group-tpsl-summary": "QuoteGroupTpSlSummary",
  "group-tpsl-side-summary": "GroupTpSlSideSummary",
  "group-tpsl-order": "GroupTpSlOrder",
  "group-tpsl-action": "GroupTpSlAction",
  "plan-group-tpsl-result": "PlanGroupTpSlResult",
  "plan-group-tpsl-delete-result": "PlanGroupTpSlDeleteResult",
  "group-tpsl-return-estimate": "GroupTpSlReturnEstimate",
};
