export default {
  index: "Overview",
  "getting-started": "Getting Started",
  concepts: "Core Concepts",
  abi: "ABI fragments",
  addresses: "Addresses",
  "account-layer": "AccountLayer",
  "instant-layer": "InstantLayer",
  "symmio-contract": "SYMMIO Contract",
  quotes: "Unified Quotes",
  margin: "Margin & Risk",
  solvers: "Solvers",
  pools: "Pools",
  inventory: "Inventory",
  tpsl: "TP/SL",
  "price-service": "Price Service",
  orderbook: "Orderbook",
  candles: "Candles",
  notifications: "Notifications",
  subgraph: "Subgraph",
  muon: "Muon Oracle",
  "shared-types": "Shared Types",
};
