export default {
  index: "Overview",
  concepts: "Core Concepts",
  abi: "ABI fragments",
  addresses: "Addresses",
  "account-layer": "AccountLayer",
  "instant-layer": "InstantLayer",
  "symmio-contract": "SYMMIO Contract",
  quotes: "Unified Quotes",
  solvers: "Solvers",
  tpsl: "TP/SL",
  "price-service": "Price Service",
  notifications: "Notifications",
  subgraph: "Subgraph",
  muon: "Muon Oracle",
  "shared-types": "Shared Types",
};
