export default {
  index: "Overview",
  "-- reads": { type: "separator", title: "Reads" },
  "get-listing-markets": "getListingMarkets",
  "get-user-listing-markets": "getUserListingMarkets",
  "user-profit": "getUserProfit",
  "deposit-address": "getDepositAddress",
  "listing-config": "getListingConfig",
  "weekly-limit": "getWeeklyListingLimit",
  "-- auth": { type: "separator", title: "Auth" },
  "listing-auth": "authenticateListing",
  "-- writes": { type: "separator", title: "Writes" },
  "add-market": "addMarket",
  "-- config": { type: "separator", title: "Config" },
  "resolve-listing-service": "resolveListingService",
  "-- helpers": { type: "separator", title: "Helpers" },
  "listing-mappers": "Mappers",
  "-- types": { type: "separator", title: "Types" },
  "listing-market-type": "ListingMarket",
};
