export default {
  index: "Overview",
  "-- reads": { type: "separator", title: "Reads" },
  "get-listing-markets": "getListingMarkets",
  "market-detail": "getListingMarketDetail",
  "get-user-listing-markets": "getUserListingMarkets",
  "user-profit": "getUserProfit",
  "claim-history": "getClaimHistory",
  "user-transactions": "getUserTransactions",
  "deposit-address": "getDepositAddress",
  "listing-status": "getListingStatus",
  "listing-config": "getListingConfig",
  "weekly-limit": "getWeeklyListingLimit",
  "-- detail": { type: "separator", title: "Pool detail" },
  "pool-detail-tables": "Detail tables",
  "pool-quotes": "getPoolQuotes",
  "pool-trade-history": "getPoolTradeHistory",
  "pool-transactions": "getPoolTransactions",
  "-- rewards": { type: "separator", title: "Rewards" },
  "pool-reward-chart": "getPoolRewardChart",
  "pool-total-reward": "getPoolTotalReward",
  "user-reward-chart": "getUserRewardChart",
  "user-total-reward": "getUserTotalReward",
  "-- auth": { type: "separator", title: "Auth" },
  "listing-auth": "authenticateListing",
  "-- writes": { type: "separator", title: "Writes" },
  "add-market": "addMarket",
  withdraw: "withdrawLp",
  "cancel-withdraw": "cancelWithdraw",
  claim: "claimProfit",
  "-- config": { type: "separator", title: "Config" },
  "resolve-listing-service": "resolveListingService",
  "-- helpers": { type: "separator", title: "Helpers" },
  "listing-mappers": "Mappers",
  "-- types": { type: "separator", title: "Types" },
  "listing-market-type": "ListingMarket",
};
