export default {
  index: "Overview",
  "getting-started": "Getting Started",
  concepts: "React Concepts",
  provider: "SymmioProvider",
  wallet: "Wallet hooks",
  "account-layer": "AccountLayer hooks",
  "instant-layer": "InstantLayer hooks",
  "symmio-contract": "SYMMIO Contract hooks",
  withdraw: "Withdraw hooks",
  quotes: "Unified Quotes",
  solvers: "Solvers hooks",
  "rasa-solver": "Rasa Solver hooks",
  tpsl: "TP/SL hooks",
  markets: "Markets hooks",
  fees: "Fees hooks",
  margin: "Margin hooks",
  "price-service": "Price Service hooks",
  orderbook: "Orderbook hooks",
  notifications: "Notifications hooks",
  subgraph: "Subgraph hooks",
  muon: "Muon Oracle hooks",
  "notional-cap": "Notional Cap hooks",
  "locked-params": "Locked Params hooks",
  "error-codes": "Error codes hooks",
  transactions: "Transactions store",
  errors: "Errors",
};
