export default {
  index: "Overview",
  "-- config": { type: "separator", title: "Config" },
  "resolve-gasless-service": "resolveGaslessService",
  "-- status": { type: "separator", title: "Request lifecycle" },
  "get-gasless-request": "getGaslessRequest",
  "get-gasless-request-transactions": "getGaslessRequestTransactions",
  "wait-for-gasless-request": "waitForGaslessRequest",
  "watch-gasless-request": "watchGaslessRequest",
  "confirm-gasless-request": "confirmGaslessRequest",
  "get-gasless-write-request": "getGaslessWriteRequest",
  "-- relay": { type: "separator", title: "Relays" },
  "relay-gasless-batch": "relayGaslessBatch",
  "relay-instant-operations": "relayInstantOperations",
  "relay-grant-delegation": "relayGrantDelegation",
  "gasless-wallet-execute": "gaslessWalletExecute",
  "resubmit-gasless-request": "resubmitGaslessRequest",
  "-- fees": { type: "separator", title: "Fees & allowance" },
  "get-gasless-batch-fee-quote": "getGaslessBatchFeeQuote",
  "get-gasless-fee-quote": "getGaslessFeeQuote",
  "get-operational-fee-allowance": "getOperationalFeeAllowance",
  "approve-operational-fee": "approveOperationalFee",
  "-- wallet": { type: "separator", title: "Gasless wallet" },
  "get-gasless-wallet-address": "getGaslessWalletAddress",
  "get-gasless-wallet-nonce": "getGaslessWalletNonce",
  "get-gasless-wallet-creation-fee": "getGaslessWalletCreationFee",
  "-- deposits": { type: "separator", title: "Deposit onboarding" },
  "get-gasless-deposit-policy": "getGaslessDepositPolicy",
  "settle-gasless-deposit-new-account": "settleGaslessDepositNewAccount",
  "settle-gasless-deposit-existing-account": "settleGaslessDepositExistingAccount",
  "-- helpers": { type: "separator", title: "Helpers" },
  "relayable-writes": "Relayable writes",
  "get-session-key-selectors": "getSessionKeySelectors",
  "get-gasless-wallet-execute-selectors": "getGaslessWalletExecuteSelectors",
  "get-gasless-batch-selectors": "getGaslessBatchSelectors",
  "errors-and-fallback": "Errors & fallback",
};
