export default {
  index: "Overview",
  "-- reads": { type: "separator", title: "Reads" },
  "get-delegation-expiry": "getDelegationExpiry",
  "get-instant-layer-nonce": "getInstantLayerNonce",
  "get-is-delegation-active": "getIsDelegationActive",
  "get-active-delegations": "getActiveDelegations",
  "get-revocation-cooldown": "getRevocationCooldown",
  "get-pending-revocation-etas": "getPendingRevocationEtas",
  "-- writes": { type: "separator", title: "Writes" },
  "grant-delegation": "grantDelegation",
  "initiate-revoke-delegation": "initiateRevokeDelegation",
  "finalize-revoke-delegation": "finalizeRevokeDelegation",
  "-- types": { type: "separator", title: "Types" },
  "instant-layer-account": "InstantLayerAccount",
};
