export default {
  index: "Overview",
  "-- types": { type: "separator", title: "Types" },
  "unified-quote": "UnifiedQuote",
  "quote-origin": "QuoteOrigin",
  "quote-lifecycle": "QuoteLifecycle",
  "quote-notification-action-kind": "QuoteNotificationActionKind",
  "-- reconciliation": { type: "separator", title: "Reconciliation" },
  "reconcile-quotes": "reconcileQuotes",
  "apply-notification-to-quotes": "applyNotificationToQuotes",
  "resolve-quote-accounts": "resolveQuoteAccounts",
  "classify-quote-notification-action": "classifyQuoteNotificationAction",
  "-- polling": { type: "separator", title: "Polling" },
  "should-accelerate-onchain-reads": "shouldAccelerateOnchainReads",
  "should-accelerate-quote-polling": "shouldAccelerateQuotePolling",
  "-- grouping": { type: "separator", title: "Grouped positions" },
  "group-quotes": "groupQuotes",
  "partition-quotes": "partitionQuotes",
  "aggregate-group-metrics": "aggregateGroupMetrics",
  "aggregate-group-funding": "aggregateGroupFunding",
  "aggregate-group-upnl": "aggregateGroupUpnl",
  "quote-group": "QuoteGroup",
  "quote-group-metrics": "QuoteGroupMetrics",
  "quote-group-funding": "QuoteGroupFunding",
  "quote-group-upnl": "QuoteGroupUpnl",
  "-- close-planning": { type: "separator", title: "Group close" },
  "to-group-close-candidates": "toGroupCloseCandidates",
  "plan-group-close": "planGroupClose",
  "-- adapters": { type: "separator", title: "Adapters" },
  "to-unified-quote-from-instant-open": "toUnifiedQuoteFromInstantOpen",
  "to-unified-quote-from-instant-close": "toUnifiedQuoteFromInstantClose",
  "to-unified-quote-from-onchain": "toUnifiedQuoteFromOnchain",
};
