export default {
  index: "Overview",
  "-- live-stream": { type: "separator", title: "Live stream" },
  "watch-notifications": "watchNotifications",
  "-- rest-search": { type: "separator", title: "REST search" },
  "search-notifications": "searchNotifications",
  "-- helpers": { type: "separator", title: "Helpers" },
  "normalize-notification": "normalizeNotification",
  "classify-notification": "classifyNotification",
  "parse-notification-frame": "parseNotificationFrame",
  "build-subscribe-message": "buildSubscribeMessage",
  "-- types": { type: "separator", title: "Types" },
  notification: "Notification",
  "raw-position-notification": "RawPositionNotification",
  "notification-type": "NotificationType",
  "notification-search-filter": "NotificationSearchFilter",
  "notification-search-result": "NotificationSearchResult",
};
