import type { CodegenConfig } from "@graphql-codegen/cli";
import { CHAIN_CONFIGS } from "./src/core/chains/registry";
import { SymmioSupportedChainId } from "./src/core/chains/supported-chains";

/**
 * graphql-codegen config for the SYMMIO subgraph layer.
 *
 * Mirrors the repo's Orval setup (`orval.config.ts`): types are generated by
 * introspecting a live canonical endpoint at generate-time, and the output is
 * committed. The raw `schema.graphql` files in `SYMM-IO/subgraphs` only declare
 * the entity models — The Graph node synthesizes the queryable `Query` root and
 * the `*_filter` / `*_orderBy` inputs at deploy time, so introspecting the
 * deployed analytics subgraph is the only source that can type a filtered
 * `quoteEvents` query.
 *
 * The endpoint is read straight from the chain registry (the SSOT for all
 * deployment URLs) rather than duplicated here. The analytics schema is shared
 * across deployments, so any supported chain types the same operations; HyperEVM
 * is the canonical one to introspect against. The registry's only runtime
 * dependency is the `SymmioSupportedChainId` enum — its `SymmioChainConfig`
 * imports are `import type` (erased), so this stays free of viem.
 *
 * Output is `documentMode: "string"`: each operation compiles to a
 * `TypedDocumentString` whose `.toString()` is the raw query text, so it POSTs
 * directly over the SDK's axios transport with zero GraphQL runtime dependency.
 */
const ANALYTICS_SUBGRAPH_URL = CHAIN_CONFIGS[SymmioSupportedChainId.HYPER_EVM].subgraphs.analytics;

const config: CodegenConfig = {
  /**
   * Live endpoint introspected at generate-time for the full executable schema
   * (Query root + Graph-generated `*_filter` / `*_orderBy` inputs). See the
   * module JSDoc for why the deployed endpoint — not the repo `schema.graphql` —
   * is the only viable source.
   */
  schema: ANALYTICS_SUBGRAPH_URL,
  /**
   * Glob set scanned for GraphQL operations to type. Operations are authored
   * inline as `graphql("…")` tagged strings anywhere under `src`. The two
   * negations keep the scan to hand-written source: tests never contribute
   * operations, and excluding the output dir stops codegen from re-parsing the
   * documents it just emitted (a self-referential loop).
   */
  documents: ["src/**/*.ts", "!src/**/*.test.ts", "!src/symmio-subgraph/types/generated/**"],
  /**
   * Don't fail the run when zero operations are found (e.g. a clean rebuild
   * before any query is authored). Keeps `pnpm generate-types` non-fatal.
   */
  ignoreNoDocuments: true,
  generates: {
    /**
     * The client preset emits a folder (`graphql.ts`, `gql.ts`, `index.ts`),
     * not a single file — hence a directory target.
     */
    "./src/symmio-subgraph/types/generated/": {
      /**
       * `client-preset` — the modern preset that emits a typed `graphql()`
       * factory returning one document per operation, replacing the legacy
       * `typescript` + `typescript-operations` + near-operation-file stack.
       */
      preset: "client",
      /**
       * Disable fragment masking so fragment fields are read directly off the
       * result type. We don't use the preset's `useFragment()` unmasking
       * indirection; the SDK consumes fields plainly.
       */
      presetConfig: { fragmentMasking: false },
      config: {
        /**
         * Each operation compiles to a `TypedDocumentString` whose `.toString()`
         * is the raw query text — POSTed directly over axios with no GraphQL
         * runtime. See the module JSDoc.
         */
        documentMode: "string",
        /**
         * Emit type-only imports as `import type { … }` so the output is
         * `verbatimModuleSyntax`/`isolatedModules`-safe and pulls in no runtime
         * imports.
         */
        useTypeImports: true,
        /**
         * The Graph custom scalars → portable TS primitives. Amounts/prices are
         * raw wei strings the actions parse to `bigint`; addresses/hashes are hex.
         */
        scalars: {
          BigInt: "string",
          Bytes: "string",
          BigDecimal: "string",
          Int8: "number",
          Timestamp: "string",
        },
      },
    },
  },
};

export default config;
