import type { CodegenConfig } from "@graphql-codegen/cli";
import { CHAIN_CONFIGS } from "./src/core/chains/registry";
import { SymmioSupportedChainId } from "./src/core/chains/supported-chains";

/**
 * graphql-codegen config for the SYMMIO subgraph layer.
 *
 * Mirrors the repo's Orval setup (`orval.config.ts`): types are generated by
 * introspecting a live canonical endpoint at generate-time, and the output is
 * committed. The raw `schema.graphql` files in `SYMM-IO/subgraphs` only declare
 * the entity models — The Graph node synthesizes the queryable `Query` root and
 * the `*_filter` / `*_orderBy` inputs at deploy time, so introspecting the
 * deployed analytics subgraph is the only source that can type a filtered
 * `quoteEvents` query.
 *
 * The endpoint is read straight from the chain registry (the SSOT for all
 * deployment URLs) rather than duplicated here. The analytics schema is shared
 * across deployments, so any supported chain types the same operations; HyperEVM
 * is the canonical one to introspect against. The registry's only runtime
 * dependency is the `SymmioSupportedChainId` enum — its `SymmioChainConfig`
 * imports are `import type` (erased), so this stays free of viem.
 *
 * Output is `documentMode: "string"`: each operation compiles to a
 * `TypedDocumentString` whose `.toString()` is the raw query text, so it POSTs
 * directly over the SDK's axios transport with zero GraphQL runtime dependency.
 */
const ANALYTICS_SUBGRAPH_URL = CHAIN_CONFIGS[SymmioSupportedChainId.HYPER_EVM].subgraphs.analytics;
/**
 * The events subgraph (raw on-chain events, e.g. `internalTransfers`). A separate
 * deployed schema from analytics, so it gets its own codegen target + output dir
 * and its operations are scoped to `src/transfers/**` (the only events consumer).
 */
const EVENTS_SUBGRAPH_URL = CHAIN_CONFIGS[SymmioSupportedChainId.HYPER_EVM].subgraphs.events;

/**
 * Shared client-preset output config — identical for both schemas. See the
 * per-field rationale below; factored out so the two targets can't drift.
 */
const CLIENT_PRESET_TARGET = {
  /**
   * `client-preset` — emits a typed `graphql()` factory returning one document
   * per operation, replacing the legacy `typescript` + `typescript-operations`
   * stack.
   */
  preset: "client",
  /**
   * Disable fragment masking so fragment fields are read directly off the result
   * type — we don't use the preset's `useFragment()` unmasking indirection.
   */
  presetConfig: { fragmentMasking: false },
  config: {
    /**
     * Each operation compiles to a `TypedDocumentString` whose `.toString()` is
     * the raw query text — POSTed directly over axios with no GraphQL runtime.
     */
    documentMode: "string",
    /** Emit type-only imports so the output is `verbatimModuleSyntax`-safe. */
    useTypeImports: true,
    /**
     * The Graph custom scalars → portable TS primitives. Amounts/prices are raw
     * wei strings the actions parse to `bigint`; addresses/hashes are hex.
     */
    scalars: {
      BigInt: "string",
      Bytes: "string",
      BigDecimal: "string",
      Int8: "number",
      Timestamp: "string",
    },
  },
} as const;

const config: CodegenConfig = {
  /**
   * Don't fail the run when zero operations are found (e.g. a clean rebuild
   * before any query is authored, or before the events slice exists). Keeps
   * `pnpm generate-types` non-fatal.
   */
  ignoreNoDocuments: true,
  generates: {
    /**
     * Analytics target. Introspects the live analytics endpoint and types every
     * `graphql("…")` operation under `src` EXCEPT the events slice — those query a
     * different schema and are typed by the events target below. The client
     * preset emits a folder (`graphql.ts`, `gql.ts`, `index.ts`), hence a
     * directory target.
     *
     * ⚠️ ROUTING IS BY FILE PATH. Both targets' generated `graphql()` factories
     * share the name `graphql`, and the client preset scans by that identifier
     * (its `gqlTagName` does not isolate a target's documents in this version), so
     * the ONLY thing that routes an operation to the right schema is the
     * `documents` globs below. **Every events operation MUST live under
     * `src/transfers/**`** (the events target's scope). To add an events consumer
     * in a new directory, add that directory to the events `documents` glob AND to
     * this target's exclusions — otherwise its `graphql("…internalTransfers…")`
     * call is swept into this analytics scan and codegen aborts with a confusing
     * "Cannot query field" error against the wrong schema.
     */
    "./src/symmio-subgraph/types/generated/analytics/": {
      schema: ANALYTICS_SUBGRAPH_URL,
      documents: ["src/**/*.ts", "!src/**/*.test.ts", "!src/symmio-subgraph/types/generated/**", "!src/transfers/**"],
      ...CLIENT_PRESET_TARGET,
    },
    /**
     * Events target. A separate deployed schema (raw on-chain events), so it gets
     * its own introspection + `graphql()` factory under a sibling `events/` output
     * dir (both schemas' generated code shares the one `types/generated/` parent).
     * Scoped to `src/transfers/**`, the only events consumer — see the path-routing
     * warning above; keep events operations under this glob and excluded from
     * analytics.
     */
    "./src/symmio-subgraph/types/generated/events/": {
      schema: EVENTS_SUBGRAPH_URL,
      documents: ["src/transfers/**/*.ts", "!src/transfers/**/*.test.ts"],
      ...CLIENT_PRESET_TARGET,
    },
  },
};

export default config;
