export default {
  index: "Overview",
  "-- markets": { type: "separator", title: "On-chain markets" },
  "get-onchain-contract-markets": "getOnchainContractMarkets",
  "-- quotes": { type: "separator", title: "Quote reads" },
  "get-quote": "getQuote",
  "get-sub-account-quotes": "getSubAccountQuotes",
  "get-party-a-open-positions": "getPartyAOpenPositions",
  "get-party-a-pending-quotes": "getPartyAPendingQuotes",
  "get-pending-quotes": "getPendingQuotes",
  "-- cancel": { type: "separator", title: "Cancel a quote" },
  "request-to-cancel-quote": "requestToCancelQuote",
  "force-cancel-quote": "forceCancelQuote",
  "get-cool-downs-of-ma": "getCoolDownsOfMA",
  "-- cancel-close": { type: "separator", title: "Cancel a close" },
  "request-to-cancel-close-request": "requestToCancelCloseRequest",
  "force-cancel-close-request": "forceCancelCloseRequest",
  "-- collateral": { type: "separator", title: "Collateral" },
  "get-collateral-balance": "getCollateralBalance",
  "get-collateral-allowance": "getCollateralAllowance",
  "-- withdraw": { type: "separator", title: "Withdraw" },
  "create-classic-withdraw-part": "createClassicWithdrawPart",
  "get-last-withdraw-request-id": "getLastWithdrawRequestId",
  "get-pending-withdraw-requests": "getPendingWithdrawRequests",
};
