export default {
  index: "Overview",
  "-- reads": { type: "separator", title: "Reads" },
  "get-user-sub-accounts": "getUserSubAccounts",
  "get-account-balance-of": "getAccountBalanceOf",
  "get-account-balance-info": "getAccountBalanceInfo",
  "-- writes": { type: "separator", title: "Writes" },
  "deposit-for-account": "depositForAccount",
  "deposit-and-allocate-for-account": "depositAndAllocateForAccount",
  allocate: "allocate",
  deallocate: "deallocate",
  "create-sub-accounts": "createSubAccounts",
  "delete-sub-account": "deleteSubAccount",
  "edit-account-name": "editAccountName",
  "-- types": { type: "separator", title: "Types" },
  "sub-account-isolation-type": "SubAccountIsolationType",
};
